server:
  port: 8080

spring:
  main.banner-mode: off
  profiles:
    active: local
  application:
    name: pricing

okta:
  oauth2:
    issuer: ${OKTA_OAUTH2_ISSUER}
    audience: api://default

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    preferIpAddress: false
