## Propriedades da aplicação
spring:
  main.banner-mode: off
  profiles:
    active: local
  application:
    name: gateway
  cloud:
    gateway:
      httpclient:
        connect-timeout: 2000
        response-timeout: 2000
      discovery:
        locator:
          enabled: true
      routes:
      - id: "cart"
        uri: lb://cart
        predicates:
        - Path=/cart/**, /carts
        filters:
          - name: Hystrix
            args:
              name: cartsFallback
              fallbackUri: forward:/carts-fallback"
        metadata:
          response-timeout: 2000
          connect-timeout: 2000

hystrix:
  command:
    cartsFallback:
      execution.isolation.thread.timeoutInMilliseconds: 2000

server:
  port: 8080

logging:
  level:
    org.springframework: INFO
    org.springframework.cloud.gateway: INFO
    reactor.netty: INFO

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    preferIpAddress: false
