## Propriedades da aplicação
spring:
  main.banner-mode: off
  profiles:
    active: local
  application:
    name: sigla-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

server:
  port: 8080

logging:
  level:
    org.springframework: INFO
    org.springframework.cloud.gateway: INFO
    reactor.netty: INFO
