# Propriedades da aplicação
spring:
  main.banner-mode: off
  profiles:
    active: local

server:
  port: 8761

logging:
  level:
    org.springframework: INFO

# Propriedades do Eureka
eureka:
  instance:
    hostname: eureka-server
  client:
    fetch-registry: false 
    register-with-eureka: false 
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/