# Propriedades da aplicação
spring:
  main.banner-mode: off
  profiles:
    active: local

server:
  port: 8761

logging:
  level:
    org.springframework: INFO

# Propriedades do Eureka
eureka:
  client:
    register-with-eureka: false