server:
  port: 8080

spring:
  main.banner-mode: off
  profiles:
    active: local
  application:
    name: cart

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OKTA_OAUTH2_ISSUER}
      client:
        registration:
          pricing-client:
            provider: okta
            authorization-grant-type: client_credentials
            scope: pricing
            client-id: ${OKTA_OAUTH2_CLIENT_ID}
            client-secret: ${OKTA_OAUTH2_CLIENT_SECRET}
        provider:
          okta:
            issuer-uri: ${OKTA_OAUTH2_ISSUER}
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

# okta:
#   oauth2:
#     issuer: ${OKTA_OAUTH2_ISSUER}
#     audience: api://default
